services:
  boxball:
    image: doublewick/boxball:postgres-cstore-fdw-latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
